colunas_variaveis = ['patent_id'
                            ,'inventors_count'
                            ,'images_count'
                            ,'backward_citations_count'
                            ,'foward_citations_count'
                            ,'nuns_count'
                            ,'aplications_count'
                            ,'top_10_words_count'
                            ,'non_patent_citations_count'
                            ,'independent_claims_count'
                            ,'application_date'
                            ,'family_count'
                            ,'ipcs_count'
                            ,'cpcs_count'
                            ,'ipcs_diversity_count'
                            ,'cpcs_diversity_count']

colunas_variaveis_treino = ['patent_id'
                            ,'inventors_count'
                            ,'images_count'
                            ,'backward_citations_count'
                            ,'nuns_count'
                            ,'aplications_count'
                            ,'top_10_words_count'
                            ,'non_patent_citations_count'
                            ,'independent_claims_count'
                            ,'application_date'
                            ,'family_count'
                            ,'ipcs_count'
                            ,'cpcs_count'
                            ,'ipcs_diversity_count'
                            ,'cpcs_diversity_count']

application_date_col = 'application_date'